### ISSUE TITLE
Implement ICollection<T> and IProducerConsumerCollection<T>

### ISSUE THREAD

**Issue by hameerabbasi** [dshulepov/ConcurrentPriorityQueue#11]

**Comment by dshulepov** [comment]
Hi.
Thanks for contributing.
But to me it seems like PriorityQueue does not really fit these interfaces. Mainly ICollection<T>.Add(T item) and IProduceConsumerCollection<T>.TryAdd(T item).
These methods take just the item as paramter, but what priority should it be then?

**Comment by hameerabbasi** [comment]
Perhaps implement: IProducerConsumerCollectiom<KeyValuePair<TPriority, TValue>>, or a specific strict/class you make. I intend to do it myself, and submit a pull request.

**Comment by dshulepov** [comment]
It's not a problem to implement these interfaces, except for the Add(T item) and TryAdd(T item) methods, because they take just the item as a parameter, while PriorityQueue requires that you provide item and priority when adding.

Could you please explain your scenario/situation/problem and why you need the implementation of these interfaces?

**Comment by hameerabbasi** [comment]
I want to use it with the BlockingCollection&lt;T&gt; class, I have a producer consumer model where I need a queue of the type you have created.

**Comment by dshulepov** [comment]
Ok, but still I don't see how it fits. 
For example, say I want to have a PriorityQueue<Task, int> to store tasks to execute with their priorities. What interface should PriorityQueue<Task, int> implement ? IProducerConsumerCollection<Task> ? 
But with what priority will the tasks be added if I call TryAdd() ?
Do you see my point?

The CuncurrentPriorityQueue is already thread safe, so you don't need a BlockingCollection<T> for thread safety.
