### ISSUE TITLE
Provide NuGet package

### ISSUE THREAD

**Issue by dshulepov** [dshulepov/ConcurrentPriorityQueue#9]

**Comment by JoshKeegan** [comment]
+1

**Comment by dshulepov** [comment]
Any suggestions on the namespace?
Currently it's just "ConcurrentPriorityQueue" which is fine if you take the sources and adapt, but it's not good for the NuGet package.

**Comment by JoshKeegan** [comment]
It doesn't matter too much in my opinion.

You can have the namespace different from the NuGet package name, so you could leave the code as-is and then put it on NuGet with a more unique project name such as CPQ.NET (or something less boring).

**Comment by dshulepov** [comment]
Done.
https://www.nuget.org/packages/PriorityQueue/
